/*
 * SensitiveView.java
 */
package sensitive;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;

/**
 * The application's main frame.
 */
public class SensitiveView extends FrameView implements ActionListener, Runnable
{
	private static ImageIcon clic1 = new ImageIcon("/home/raphael/Documents/code/PR302/img/1clic.png");
	private static ImageIcon clic2 = new ImageIcon("/home/raphael/Documents/code/PR302/img/2clic.png");
	private static ImageIcon clic3 = new ImageIcon("/home/raphael/Documents/code/PR302/img/3clic.png");
	private static ImageIcon clic4 = new ImageIcon("/home/raphael/Documents/code/PR302/img/4clic.png");
	private static ImageIcon vert1 = new ImageIcon("/home/raphael/Documents/code/PR302/img/1vert.png");
	private static ImageIcon vert2 = new ImageIcon("/home/raphael/Documents/code/PR302/img/2vert.png");
	private static ImageIcon vert3 = new ImageIcon("/home/raphael/Documents/code/PR302/img/3vert.png");
	private static ImageIcon vert4 = new ImageIcon("/home/raphael/Documents/code/PR302/img/4vert.png");
	
	public SensitiveView(SingleFrameApplication app)
	{
		super(app);
		initComponents();
		Thread t = new Thread(this);
		t.start();
	}
	
	public void run()
	{		
		Capture capture = new Capture();
		ArrayList<Bouton> btns = new ArrayList<Bouton>();

		for (int k = 1; k <= 4; k++)
		{
			System.out.println("bouton " + k);
			Bouton b = new Bouton(capture);
			btns.add(b);
			b.addListener(this);
		}
		System.out.println();

		while (true)
		{
			Bouton.traiterSignal(capture.getTap(), btns);
		}
	}
		
	public void actionPerformed(ActionEvent ae)
	{
		JButton b;
		ImageIcon on;
		ImageIcon off;
		switch (ae.getID() + 1)
		{
			case 1:
				b = jButton1;
				on = clic1;
				off = vert1;
				break;
			case 2:
				b = jButton2;
				on = clic2;
				off = vert2;
				break;
			case 3:
				b = jButton3;
				on = clic3;
				off = vert3;
				break;
			case 4:
				b = jButton4;
				on = clic4;
				off = vert4;
				break;
			default:
				System.out.println("rien");
				return;
			}

		b.setIcon(on);
		try
		{
			Thread.sleep(500);
		}
		catch (InterruptedException ex)
		{			
			System.out.println("Interruption de l'attente");
		}
		b.setIcon(off);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sensitive.SensitiveApp.class).getContext().getResourceMap(SensitiveView.class);
        jButton1.setBackground(resourceMap.getColor("jButton1.background")); // NOI18N
        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(85, 85));
        jButton1.setMinimumSize(new java.awt.Dimension(85, 85));
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(160, 160));

        jButton2.setBackground(resourceMap.getColor("jButton4.background")); // NOI18N
        jButton2.setIcon(resourceMap.getIcon("jButton2.icon")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(160, 160));

        jButton3.setBackground(resourceMap.getColor("jButton4.background")); // NOI18N
        jButton3.setIcon(resourceMap.getIcon("jButton3.icon")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.setPreferredSize(new java.awt.Dimension(160, 160));

        jButton4.setBackground(resourceMap.getColor("jButton4.background")); // NOI18N
        jButton4.setIcon(resourceMap.getIcon("jButton4.icon")); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.setPreferredSize(new java.awt.Dimension(160, 160));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(233, 233, 233)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        setComponent(mainPanel);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
